version: '3.8'

services:
  mcp-rancher-multi:
    build: .
    container_name: mcp-rancher-multi
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - ENABLE_FILE_LOGGING=false
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('MCP Server is healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: mcp-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - mcp-network

networks:
  mcp-network:
    driver: bridge

# volumes:
#   redis-data:
